apiVersion: v1
# 1. ServiceAccount: "Web Pod의 신분증"
kind: ServiceAccount
metadata:
  name: web-sa
  namespace: stock-backtest
  labels:
    app: web
    app.kubernetes.io/name: stock-backtest
---
apiVersion: rbac.authorization.k8s.io/v1
# 2. Role: "이 신분증으로 할 수 있는 것"
kind: Role
metadata:
  name: web-job-manager
  namespace: stock-backtest
  labels:
    app: web
    app.kubernetes.io/name: stock-backtest
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
    # jobs를 만들고, 조회하고, 삭제할 수 있다.
---

apiVersion: rbac.authorization.k8s.io/v1
# 3. RoleBinding: "이 신분증에 이 역할을 부여"
kind: RoleBinding
metadata:
  name: web-job-manager-binding
  namespace: stock-backtest
  labels:
    app: web
    app.kubernetes.io/name: stock-backtest
subjects:
  - kind: ServiceAccount
    name: web-sa # web pod가 사용할 ServiceAccount
    namespace: stock-backtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # RoleBinding이 참조하는 역할의 종류 (Role 또는 ClusterRole)
  name: web-job-manager
