apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: stock-backtest
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: web-sa
      containers:
        - name: web
          image: stock-web:local 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: web-config
            - secretRef:
                name: web-secret
          env:
            - name: JOB_LAUNCHER_MODE
              value: "K8S" # k8s or LOCAL // LOCAL은 개발용, K8S는 실제 클러스터에서 실행할 때 사용
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
